package it.vitalegi.archi.model;

public enum ElementType {
    PERSON, SOFTWARE_SYSTEM, CONTAINER, GROUP, DEPLOYMENT_ENVIRONMENT, DEPLOYMENT_NODE, CONTAINER_INSTANCE, SOFTWARE_SYSTEM_INSTANCE, INFRASTRUCTURE_NODE, RELATION

}
