package it.vitalegi.archi.model.element;

public enum ElementType {
    PERSON, SOFTWARE_SYSTEM, CONTAINER, COMPONENT, GROUP, DEPLOYMENT_ENVIRONMENT, DEPLOYMENT_NODE, CONTAINER_INSTANCE, SOFTWARE_SYSTEM_INSTANCE, INFRASTRUCTURE_NODE, RELATION, IMPLICIT_RELATION

}
